### ISSUE TITLE
SDK crash on startup due to null settings object

### ISSUE THREAD

**Issue by ahinkka** [audienceproject/userreport-android-sdk#13]
We have seen lots of crashes on a few users (e.g. 1.4k crashes on 4 users during the past week) in our public open beta group (~6.4k users).

This is currently blocking a release of our app. The release would bring audience measurements into the app. Details on what this is actually blocking will be relayed via other means and further prioritization is out of scope of this rather technical issue description.

SDK version: 1.0.0.5 (Gradle says `implementation 'com.audienceproject:userreport:1.0.0.5'`)
Environment: Android 9 & Android 10 (at least)
Devices where this has been seen: Samsung Galaxy S9+, Android 9 & 10:

All the crashes have been in the background.

Stack trace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.audienceproject.userreport.models.Settings.getLocalQuarantineDays()' on a null object reference
       at com.audienceproject.userreport.UserReportSettingsLoader.raiseSettingsLoaded(UserReportSettingsLoader.java:83)
       at com.audienceproject.userreport.UserReportSettingsLoader.lambda$loadSAKSettings$0(UserReportSettingsLoader.java:157)
       at com.audienceproject.userreport.UserReportSettingsLoader.lambda$loadSAKSettings$0$UserReportSettingsLoader(UserReportSettingsLoader.java)
       at com.audienceproject.userreport.-$$Lambda$UserReportSettingsLoader$K8Q3Sv9Kvf58898m2vo4li_5P5o.onResponse(-.java:4)
       at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
       at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

## Further analysis

We (me & @miikkajs) analyzed the issue and believe the culprit to be [line 86](https://github.com/audienceproject/userreport-android-sdk/blob/e2c18f380089b72b7a06ada9d3178c1249a2ee47/Userreport-survey/userreport/src/main/java/com/audienceproject/userreport/UserReportSettingsLoader.java#L86) in `UserReportSettingsLoader.java`, in `raiseSettingsLoaded` method.

The larger context is this:
```
resultSettings.setLocalQuarantineDays(userSettings != null
        && userSettings.getLocalQuarantineDays() != null
        ? userSettings.getLocalQuarantineDays()
        : sakSettings.getLocalQuarantineDays() != null
        ? sakSettings.getLocalQuarantineDays()
        : Settings.getDefaultSettings().getLocalQuarantineDays());
```

It seems that `sakSettings` is null, and we don't actually check that it's null here - I'm guessing from the context that that was probably the intention, but got lost in the depths of the ternary chain. I'm guessing the simplest fix for that would be to change `: sakSettings.getLocalQuarantineDays() != null` into `: sakSettings != null && sakSettings.getLocalQuarantineDays() != null` on line 4 of the code listing above to match how `userSettings` is handled on lines 1 and 2.

If I understand the code correctly, it seems that `userSettings` can very well be null - it's only initialized if the SDK is initialized with that as the parameter. In our case we don't pass it in, but initialize it as follows:
```
fun init(application: Application) {
    this.userReport = try {
        val result = UserReport.configure(application, "<redacted>", mediaId)
        Timber.i("UserReport initialized")
        result
    } catch (t: Throwable) {
        FirebaseCrashlytics.getInstance().recordException(t)
        null
    }
}
```

We got a little side-tracked by the different class of `sakSettings` (MediaSettings), which is not what the stack trace mentions. However, my colleague noticed it actually inherits from the class named in the stack trace.

## Why is the settings object null?

The ternary chain's intention seems to be to guard against not having any configuration, but it's a bit curious reading the code how that could be the case. SAK settings are either loaded from shared preferences, or fetched by `loadSAKSettings` from the server. Reading the code it's not clear how the object could be null as `raiseSettingsLoaded` is not called without an initialized settings object as there are guards against that on lines [73](https://github.com/audienceproject/userreport-android-sdk/blob/e2c18f380089b72b7a06ada9d3178c1249a2ee47/Userreport-survey/userreport/src/main/java/com/audienceproject/userreport/UserReportSettingsLoader.java#L73) and [155](https://github.com/audienceproject/userreport-android-sdk/blob/e2c18f380089b72b7a06ada9d3178c1249a2ee47/Userreport-survey/userreport/src/main/java/com/audienceproject/userreport/UserReportSettingsLoader.java#L155).

https://github.com/audienceproject/userreport-android-sdk/blob/e2c18f380089b72b7a06ada9d3178c1249a2ee47/Userreport-survey/userreport/src/main/java/com/audienceproject/userreport/UserReportSettingsLoader.java#L71-L78

https://github.com/audienceproject/userreport-android-sdk/blob/e2c18f380089b72b7a06ada9d3178c1249a2ee47/Userreport-survey/userreport/src/main/java/com/audienceproject/userreport/UserReportSettingsLoader.java#L151-L167

The latter code block, the response handler in `loadSAKSettings` reads as if the result is expected to be valid - and that if the deserialization done in `parseData` fails, it throws an exception and calls `raiseSettingsLoaded`. Diving deeper into `parseData` and further into the underlying Gson's `fromJson` method, it became apparent that [in case the response body contained either a JSON null or the response body was empty, it would deserialize into a null](https://github.com/google/gson/blob/gson-parent-2.8.6/gson/src/main/java/com/google/gson/Gson.java#L811).

We ended our research at this point. As the crashes are happening in our open beta group, and only for a few users, we unfortunately cannot provide any quick testing to this issue. A fix would need to be pushed out and tested over time. If the problem is the backend returning an empty or null response, naturally the quickest way for us to get into production with a new app release would be to fix that. However, we would like to see at least the missing null check fixed as well as it's a clear instability factor for our app, and any other apps that use the SDK. For understanding the code, it probably also makes sense to also make changes to the way the deserialization result is trusted.

**Comment by hmvs** [comment]
Hi, thank you very much for such a detailed bug report. We will deliver a fix early next week. I will keep you posted.

**Comment by ahinkka** [comment]
Thanks! Communicated to the rest of the organization. 🙇

**Comment by hmvs** [comment]
Hi @ahinkka, can you please send me `PUBLISHER_ID` and `mediaId`  from this line `val result = UserReport.configure(application, "<redacted>", mediaId)`.  Send it please to vk@audienceproject.com

**Comment by ahinkka** [comment]
> Hi @ahinkka, can you please send me `PUBLISHER_ID` and `mediaId` from this line `val result = UserReport.configure(application, "<redacted>", mediaId)`. Send it please to vk [at] audienceproject.com

Sent!

**Comment by hmvs** [comment]
We haven't identified the root cause of why we wouldn't get the correct JSON there, so we put another guard on the settings (version 1.0.0.6).
Thanks again for the analysis and report by itself.
