### ISSUE TITLE
Update Volley dependency to 1.2.0

### ISSUE THREAD

**Issue by Zudoku** [audienceproject/userreport-android-sdk#16]
Hey! would it be possible to have the [volley dependency](https://github.com/audienceproject/userreport-android-sdk/blob/master/Userreport-survey/userreport/build.gradle#L183) updated to 1.2.0?

https://github.com/google/volley/releases/tag/1.2.0

We are trying to remove JCenter repository from our project and noticed that the `com.android.volley:volley:1.1.1` dependency included in the UserReport SDK can only be found in JCenter or from repositories that we do not trust. Since 1.2.0 is found in Maven Central, updating that dependency would enable us to ditch JCenter completely, as well as add the bug fixes in the 1.2.0 release. 

Here is some more information about the JCenter migration: https://developer.android.com/studio/build/jcenter-migration

**Comment by hmvs** [comment]
We've released version 1.0.0.7 with an updated dependency. Thanks for the report.

**Comment by Zudoku** [comment]
Awesome, thanks! :-)
